import stationsData from "./stations.json";

/** Tested contract: station lookup/search is case-insensitive and deterministic. */

export type Station = {
  /** STATION_2CHAR, the code the departures API expects (e.g. "NY"). */
  code: string;
  name: string;
  lat: number;
  lng: number;
  /** Line codes serving this station, e.g. ["NC", "NE"]. */
  lines: string[];
};

/** Every NJT rail station, sorted by name. Generated by scripts/build-stations.mjs. */
export const stations: Station[] = stationsData;

const byCode = new Map(stations.map((s) => [s.code, s]));

export function getStation(code: string): Station | undefined {
  return byCode.get(code.toUpperCase());
}

/** Line code -> full name, from Appendix VI of the RailData API manual. */
export const LINE_NAMES: Record<string, string> = {
  AC: "Atlantic City Line",
  AM: "Amtrak",
  BC: "Bergen County Line",
  GS: "Gladstone Branch",
  MC: "Montclair-Boonton Line",
  ME: "Morris & Essex Line",
  ML: "Main Line",
  NC: "North Jersey Coast Line",
  NE: "Northeast Corridor Line",
  PR: "Princeton Branch",
  PV: "Pascack Valley Line",
  RV: "Raritan Valley Line",
  SL: "BetMGM Meadowlands",
  SP: "SEPTA",
};

export function lineName(code: string): string {
  return LINE_NAMES[code] ?? code;
}

/**
 * NJ Transit's own line colours, taken from the rail map data behind
 * njtransit.com, so a line reads the same here as on station signage.
 * Princeton shares the Northeast Corridor's colour, as it does on NJT's map.
 */
export const LINE_COLORS: Record<string, string> = {
  AC: "#2E55A5",
  BC: "#98A8BF",
  GS: "#A1D5AE",
  MC: "#C36366",
  ME: "#00953B",
  ML: "#F2B826",
  NC: "#009CDB",
  NE: "#F7505E",
  PR: "#F7505E",
  PV: "#A34F8B",
  RV: "#FF993E",
  SL: "#6B7280",
};

export function lineColor(code: string): string {
  return LINE_COLORS[code] ?? "#6B7280";
}

const EARTH_RADIUS_KM = 6371;
const toRad = (deg: number) => (deg * Math.PI) / 180;

/** Great-circle distance in kilometres. */
export function distanceKm(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number,
): number {
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(a));
}

/** The station closest to a coordinate, with its distance. */
export function nearestStation(
  lat: number,
  lng: number,
): { station: Station; distanceKm: number } {
  let best = stations[0];
  let bestDistance = Infinity;
  for (const station of stations) {
    const d = distanceKm(lat, lng, station.lat, station.lng);
    if (d < bestDistance) {
      best = station;
      bestDistance = d;
    }
  }
  return { station: best, distanceKm: bestDistance };
}

const normalize = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    // Fold punctuation so "Glen Rock-Boro Hall" matches "glen rock boro hall".
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

/**
 * Stations matching a search query, ranked so that name-prefix matches come
 * first, then word-prefix matches, then anything else containing the query.
 * An exact station code (e.g. "NY") always ranks first.
 */
export function searchStations(query: string, limit = 12): Station[] {
  const q = normalize(query);
  if (!q) return [];

  const scored: { station: Station; score: number }[] = [];
  for (const station of stations) {
    const name = normalize(station.name);
    let score: number;
    if (station.code.toLowerCase() === q) score = 0;
    else if (name.startsWith(q)) score = 1;
    else if (name.split(" ").some((word) => word.startsWith(q))) score = 2;
    else if (name.includes(q)) score = 3;
    else continue;
    scored.push({ station, score });
  }

  scored.sort(
    (a, b) =>
      a.score - b.score || a.station.name.localeCompare(b.station.name),
  );
  return scored.slice(0, limit).map((s) => s.station);
}
